
//
// Copyright (C) 2025 voidtools / David Carpenter
// 
// Permission is hereby granted, free of charge, 
// to any person obtaining a copy of this software 
// and associated documentation files (the "Software"), 
// to deal in the Software without restriction, 
// including without limitation the rights to use, 
// copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit 
// persons to whom the Software is furnished to do so, 
// subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be 
// included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// #define _PROPERTY_OLD_COLUMN_MACRO(property_id)

PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_PATH_AND_NAME) // ES_COLUMN_FILENAME,
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_NAME) // ES_COLUMN_NAME
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_PATH) // ES_COLUMN_PATH
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_PATH_AND_NAME) // ES_COLUMN_HIGHLIGHTED_FILENAME
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_NAME) // ES_COLUMN_HIGHLIGHTED_NAME
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_PATH) // ES_COLUMN_HIGHLIGHTED_PATH
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_EXTENSION) // ES_COLUMN_EXTENSION
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_SIZE) // ES_COLUMN_SIZE
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_DATE_CREATED) // ES_COLUMN_DATE_CREATED
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_DATE_MODIFIED) // ES_COLUMN_DATE_MODIFIED
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_DATE_ACCESSED) // ES_COLUMN_DATE_ACCESSED
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_ATTRIBUTES) // ES_COLUMN_ATTRIBUTES
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_FILE_LIST_NAME) // ES_COLUMN_FILE_LIST_FILENAME
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_RUN_COUNT) // ES_COLUMN_RUN_COUNT
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_DATE_RUN) // ES_COLUMN_DATE_RUN
PROPERTY_OLD_COLUMN_MACRO(EVERYTHING3_PROPERTY_ID_DATE_RECENTLY_CHANGED) // ES_COLUMN_DATE_RECENTLY_CHANGED
