
#define VERSION_YEAR			2025
#define VERSION_MAJOR 			1
#define VERSION_MINOR 			1
#define VERSION_REVISION		0
#define VERSION_BUILD			35
#define VERSION_TYPE			""

#define _VERSION_TEXT_STR2(x)	#x
#define _VERSION_TEXT_STR(x)	_VERSION_TEXT_STR2(x)
#define VERSION_TEXT			_VERSION_TEXT_STR(VERSION_MAJOR) "." _VERSION_TEXT_STR(VERSION_MINOR) "." _VERSION_TEXT_STR(VERSION_REVISION) "." _VERSION_TEXT_STR(VERSION_BUILD) VERSION_TYPE
#define VERSION_YEAR_TEXT		_VERSION_TEXT_STR(VERSION_YEAR)
